export const mockCompanies = [
  {
    id: 'comp-1',
    name: 'ТехноСтар',
    logo: null,
    isActive: true,
    createdAt: new Date('2025-01-15'),
    updatedAt: new Date('2025-01-15'),
  },
  {
    id: 'comp-2',
    name: 'ИнноВижн',
    logo: null,
    isActive: true,
    createdAt: new Date('2025-02-20'),
    updatedAt: new Date('2025-02-20'),
  },
  {
    id: 'comp-3',
    name: 'ДатаПро',
    logo: null,
    isActive: false,
    createdAt: new Date('2025-03-10'),
    updatedAt: new Date('2025-05-01'),
  },
]

export const mockUsers = [
  {
    id: 'user-super',
    email: 'super@skf.ru',
    passwordHash: '$2a$10$dummyhash',
    name: 'Главный Администратор',
    role: 'super_admin' as const,
    companyId: null,
    personalToken: null,
    isActive: true,
    lastLoginAt: new Date(),
    createdAt: new Date('2025-01-01'),
  },
  {
    id: 'user-admin-1',
    email: 'admin@technostar.ru',
    passwordHash: '$2a$10$dummyhash',
    name: 'Анна Козлова',
    role: 'company_admin' as const,
    companyId: 'comp-1',
    personalToken: null,
    isActive: true,
    lastLoginAt: new Date(),
    createdAt: new Date('2025-01-16'),
  },
  {
    id: 'user-admin-2',
    email: 'admin@innovision.ru',
    passwordHash: '$2a$10$dummyhash',
    name: 'Дмитрий Петров',
    role: 'company_admin' as const,
    companyId: 'comp-2',
    personalToken: null,
    isActive: true,
    lastLoginAt: new Date(),
    createdAt: new Date('2025-02-21'),
  },
  {
    id: 'emp-1',
    email: null,
    passwordHash: null,
    name: 'Иван Сидоров',
    role: 'employee' as const,
    companyId: 'comp-1',
    personalToken: 'token-ivan-abc123',
    isActive: true,
    lastLoginAt: new Date('2025-05-20'),
    createdAt: new Date('2025-02-01'),
  },
  {
    id: 'emp-2',
    email: null,
    passwordHash: null,
    name: 'Мария Иванова',
    role: 'employee' as const,
    companyId: 'comp-1',
    personalToken: 'token-maria-def456',
    isActive: true,
    lastLoginAt: new Date('2025-05-18'),
    createdAt: new Date('2025-02-05'),
  },
  {
    id: 'emp-3',
    email: null,
    passwordHash: null,
    name: 'Алексей Волков',
    role: 'employee' as const,
    companyId: 'comp-1',
    personalToken: 'token-alex-ghi789',
    isActive: true,
    lastLoginAt: new Date('2025-05-15'),
    createdAt: new Date('2025-02-10'),
  },
  {
    id: 'emp-4',
    email: null,
    passwordHash: null,
    name: 'Елена Смирнова',
    role: 'employee' as const,
    companyId: 'comp-1',
    personalToken: 'token-elena-jkl012',
    isActive: true,
    lastLoginAt: null,
    createdAt: new Date('2025-03-01'),
  },
  {
    id: 'emp-5',
    email: null,
    passwordHash: null,
    name: 'Сергей Кузнецов',
    role: 'employee' as const,
    companyId: 'comp-2',
    personalToken: 'token-sergey-mno345',
    isActive: true,
    lastLoginAt: new Date('2025-05-19'),
    createdAt: new Date('2025-03-05'),
  },
  {
    id: 'emp-6',
    email: null,
    passwordHash: null,
    name: 'Ольга Новикова',
    role: 'employee' as const,
    companyId: 'comp-2',
    personalToken: 'token-olga-pqr678',
    isActive: true,
    lastLoginAt: new Date('2025-05-10'),
    createdAt: new Date('2025-03-10'),
  },
]

export const mockCourses = [
  {
    id: 'course-1',
    companyId: 'comp-1',
    title: 'Основы информационной безопасности',
    description: 'Комплексный курс по основам защиты информации на предприятии. Включает темы: фишинг, пароли, социальная инженерия.',
    coverImage: null,
    isPublished: true,
    createdAt: new Date('2025-02-01'),
  },
  {
    id: 'course-2',
    companyId: 'comp-1',
    title: 'Работа с персональными данными',
    description: 'Правила обработки персональных данных в соответствии с 152-ФЗ.',
    coverImage: null,
    isPublished: true,
    createdAt: new Date('2025-03-01'),
  },
  {
    id: 'course-3',
    companyId: 'comp-2',
    title: 'Техника безопасности на производстве',
    description: 'Обязательный инструктаж по технике безопасности.',
    coverImage: null,
    isPublished: true,
    createdAt: new Date('2025-03-15'),
  },
]

export const mockLessons = [
  {
    id: 'lesson-1',
    courseId: 'course-1',
    title: 'Что такое информационная безопасность',
    description: 'Введение в основные понятия и принципы ИБ',
    vimeoId: null,
    duration: 480,
    orderIndex: 0,
    coverImage: null,
  },
  {
    id: 'lesson-2',
    courseId: 'course-1',
    title: 'Фишинг и социальная инженерия',
    description: 'Как распознать фишинговые атаки и защититься от них',
    vimeoId: null,
    duration: 600,
    orderIndex: 1,
    coverImage: null,
  },
  {
    id: 'lesson-3',
    courseId: 'course-1',
    title: 'Безопасные пароли',
    description: 'Правила создания и хранения надежных паролей',
    vimeoId: null,
    duration: 360,
    orderIndex: 2,
    coverImage: null,
  },
  {
    id: 'lesson-4',
    courseId: 'course-2',
    title: 'Основы 152-ФЗ',
    description: 'Законодательная база по работе с персональными данными',
    vimeoId: null,
    duration: 540,
    orderIndex: 0,
    coverImage: null,
  },
  {
    id: 'lesson-5',
    courseId: 'course-3',
    title: 'Общие правила ТБ',
    description: 'Основные правила техники безопасности',
    vimeoId: null,
    duration: 420,
    orderIndex: 0,
    coverImage: null,
  },
]

export const mockQuestions = [
  {
    id: 'q-1',
    lessonId: 'lesson-1',
    text: 'Что является основной целью информационной безопасности?',
    options: JSON.stringify([
      'Увеличение скорости интернета',
      'Защита информации от несанкционированного доступа',
      'Установка антивирусов',
      'Блокировка всех сайтов'
    ]),
    correctIndex: 1,
    timecodeStart: 30,
    timecodeTrigger: 120,
    orderIndex: 0,
  },
  {
    id: 'q-2',
    lessonId: 'lesson-1',
    text: 'Какие три ключевых принципа ИБ существуют?',
    options: JSON.stringify([
      'Скорость, надежность, доступность',
      'Конфиденциальность, целостность, доступность',
      'Шифрование, авторизация, аудит',
      'Защита, контроль, мониторинг'
    ]),
    correctIndex: 1,
    timecodeStart: 180,
    timecodeTrigger: 300,
    orderIndex: 1,
  },
  {
    id: 'q-3',
    lessonId: 'lesson-2',
    text: 'Какой из признаков указывает на фишинговое письмо?',
    options: JSON.stringify([
      'Письмо от знакомого коллеги',
      'Срочная просьба перейти по ссылке и ввести пароль',
      'Рассылка с корпоративного сервера',
      'Письмо с вложенным документом из бухгалтерии'
    ]),
    correctIndex: 1,
    timecodeStart: 60,
    timecodeTrigger: 180,
    orderIndex: 0,
  },
  {
    id: 'q-4',
    lessonId: 'lesson-3',
    text: 'Какой пароль считается надежным?',
    options: JSON.stringify([
      'password123',
      'Дата рождения',
      'Комбинация из 12+ символов с буквами, цифрами и спецсимволами',
      'Имя питомца'
    ]),
    correctIndex: 2,
    timecodeStart: 30,
    timecodeTrigger: 120,
    orderIndex: 0,
  },
]

export const mockLessonProgress = [
  { id: 'lp-1', userId: 'emp-1', lessonId: 'lesson-1', status: 'passed' as const, maxWatchedPosition: 480, attemptCount: 1, completedAt: new Date('2025-05-10') },
  { id: 'lp-2', userId: 'emp-1', lessonId: 'lesson-2', status: 'passed' as const, maxWatchedPosition: 600, attemptCount: 2, completedAt: new Date('2025-05-12') },
  { id: 'lp-3', userId: 'emp-1', lessonId: 'lesson-3', status: 'in_progress' as const, maxWatchedPosition: 180, attemptCount: 0, completedAt: null },
  { id: 'lp-4', userId: 'emp-2', lessonId: 'lesson-1', status: 'passed' as const, maxWatchedPosition: 480, attemptCount: 1, completedAt: new Date('2025-05-15') },
  { id: 'lp-5', userId: 'emp-2', lessonId: 'lesson-2', status: 'in_progress' as const, maxWatchedPosition: 300, attemptCount: 0, completedAt: null },
  { id: 'lp-6', userId: 'emp-3', lessonId: 'lesson-1', status: 'passed' as const, maxWatchedPosition: 480, attemptCount: 3, completedAt: new Date('2025-05-18') },
  { id: 'lp-7', userId: 'emp-5', lessonId: 'lesson-5', status: 'passed' as const, maxWatchedPosition: 420, attemptCount: 1, completedAt: new Date('2025-05-16') },
]

export const mockCourseAssignments = [
  { id: 'ca-1', userId: 'emp-1', courseId: 'course-1', assignedAt: new Date('2025-02-05') },
  { id: 'ca-2', userId: 'emp-1', courseId: 'course-2', assignedAt: new Date('2025-03-05') },
  { id: 'ca-3', userId: 'emp-2', courseId: 'course-1', assignedAt: new Date('2025-02-10') },
  { id: 'ca-4', userId: 'emp-3', courseId: 'course-1', assignedAt: new Date('2025-02-15') },
  { id: 'ca-5', userId: 'emp-4', courseId: 'course-1', assignedAt: new Date('2025-03-05') },
  { id: 'ca-6', userId: 'emp-5', courseId: 'course-3', assignedAt: new Date('2025-03-20') },
  { id: 'ca-7', userId: 'emp-6', courseId: 'course-3', assignedAt: new Date('2025-03-20') },
]

export const mockActivityLog = Array.from({ length: 14 }, (_, i) => ({
  date: new Date(Date.now() - (13 - i) * 86400000).toISOString().split('T')[0],
  logins: Math.floor(Math.random() * 8) + 1,
  lessonsCompleted: Math.floor(Math.random() * 5),
  questionsAnswered: Math.floor(Math.random() * 12) + 2,
}))
