/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SuperRouteRouteImport } from './routes/super/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperIndexRouteImport } from './routes/super/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as LearnTokenRouteImport } from './routes/learn/$token'
import { Route as AdminStatisticsRouteImport } from './routes/admin/statistics'
import { Route as AdminEmployeesRouteImport } from './routes/admin/employees'
import { Route as AdminCoursesIndexRouteImport } from './routes/admin/courses/index'
import { Route as AdminCoursesCourseIdRouteImport } from './routes/admin/courses/$courseId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperRouteRoute = SuperRouteRouteImport.update({
  id: '/super',
  path: '/super',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperIndexRoute = SuperIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const LearnTokenRoute = LearnTokenRouteImport.update({
  id: '/learn/$token',
  path: '/learn/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStatisticsRoute = AdminStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCoursesIndexRoute = AdminCoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCoursesCourseIdRoute = AdminCoursesCourseIdRouteImport.update({
  id: '/courses/$courseId',
  path: '/courses/$courseId',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/super': typeof SuperRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/statistics': typeof AdminStatisticsRoute
  '/learn/$token': typeof LearnTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/super/': typeof SuperIndexRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/statistics': typeof AdminStatisticsRoute
  '/learn/$token': typeof LearnTokenRoute
  '/admin': typeof AdminIndexRoute
  '/super': typeof SuperIndexRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdRoute
  '/admin/courses': typeof AdminCoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/super': typeof SuperRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/statistics': typeof AdminStatisticsRoute
  '/learn/$token': typeof LearnTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/super/': typeof SuperIndexRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/super'
    | '/login'
    | '/admin/employees'
    | '/admin/statistics'
    | '/learn/$token'
    | '/admin/'
    | '/super/'
    | '/admin/courses/$courseId'
    | '/admin/courses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/employees'
    | '/admin/statistics'
    | '/learn/$token'
    | '/admin'
    | '/super'
    | '/admin/courses/$courseId'
    | '/admin/courses'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/super'
    | '/login'
    | '/admin/employees'
    | '/admin/statistics'
    | '/learn/$token'
    | '/admin/'
    | '/super/'
    | '/admin/courses/$courseId'
    | '/admin/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  SuperRouteRoute: typeof SuperRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  LearnTokenRoute: typeof LearnTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super': {
      id: '/super'
      path: '/super'
      fullPath: '/super'
      preLoaderRoute: typeof SuperRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/': {
      id: '/super/'
      path: '/'
      fullPath: '/super/'
      preLoaderRoute: typeof SuperIndexRouteImport
      parentRoute: typeof SuperRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/learn/$token': {
      id: '/learn/$token'
      path: '/learn/$token'
      fullPath: '/learn/$token'
      preLoaderRoute: typeof LearnTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/statistics': {
      id: '/admin/statistics'
      path: '/statistics'
      fullPath: '/admin/statistics'
      preLoaderRoute: typeof AdminStatisticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/courses/': {
      id: '/admin/courses/'
      path: '/courses'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AdminCoursesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/courses/$courseId': {
      id: '/admin/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/admin/courses/$courseId'
      preLoaderRoute: typeof AdminCoursesCourseIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminEmployeesRoute: typeof AdminEmployeesRoute
  AdminStatisticsRoute: typeof AdminStatisticsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCoursesCourseIdRoute: typeof AdminCoursesCourseIdRoute
  AdminCoursesIndexRoute: typeof AdminCoursesIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminEmployeesRoute: AdminEmployeesRoute,
  AdminStatisticsRoute: AdminStatisticsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCoursesCourseIdRoute: AdminCoursesCourseIdRoute,
  AdminCoursesIndexRoute: AdminCoursesIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface SuperRouteRouteChildren {
  SuperIndexRoute: typeof SuperIndexRoute
}

const SuperRouteRouteChildren: SuperRouteRouteChildren = {
  SuperIndexRoute: SuperIndexRoute,
}

const SuperRouteRouteWithChildren = SuperRouteRoute._addFileChildren(
  SuperRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  SuperRouteRoute: SuperRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  LearnTokenRoute: LearnTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
